name: Terraform Deploy

on:

  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice
        options:
          - qa
          - prod
      
jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    outputs:
      changes: ${{ steps.show.outputs.changes }}

    defaults:
      run:
        working-directory: infra/envs/${{ github.event.inputs.environment }}

    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Terraform Cloud token
        id: check_token
        run: |
          if [ -z "${{ secrets.MYAPP_TFE_TOKEN }}" ]; then
            echo "TOKEN_EXISTS=false" >> $GITHUB_ENV
          else
            echo "TOKEN_EXISTS=true" >> $GITHUB_ENV
          fi

      - name: Setup Terraform
        if: env.TOKEN_EXISTS == 'true'
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.0
          cli_config_credentials_token: ${{ secrets.MYAPP_TFE_TOKEN }}

      - name: Terraform Format Check
        if: env.TOKEN_EXISTS == 'true'
        run: terraform fmt -check

      - name: Terraform Init
        if: env.TOKEN_EXISTS == 'true'
        run: terraform init

      - name: Terraform Validate
        if: env.TOKEN_EXISTS == 'true'
        run: terraform validate


      - name: Terraform Plan
        run: terraform plan -no-color -out=tfplan

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/envs/${{ github.event.inputs.environment }}/tfplan



  terraform-apply:
    name: Terraform Apply
    needs: terraform-plan

    if: github.event_name != 'pull_request'

    runs-on: ubuntu-latest

    environment: ${{ github.event.inputs.environment }}

    defaults:
      run:
        working-directory: infra/envs/${{ github.event.inputs.environment }}

    env:
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/envs/${{ github.event.inputs.environment }}

      - name: Setup Terraform
        if: env.TOKEN_EXISTS == 'true'
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.0
          cli_config_credentials_token: ${{ secrets.MYAPP_TFE_TOKEN }}


      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
