name: terraform-plan


on:
  pull_request:
    branches:
      - develop
  

  workflow_dispatch:
    inputs:
      ENV:
        description: "Target environment"
        required: true
        type: choice
        options:
          - dev
        default: dev
      APP:
        description: "Application identifier"
        required: true
        type: choice
        options:
          - myapp

jobs:
  terraform-plan:
    name: Terraform CI - Plan
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENV || 'dev' }}

    env:
      TF_IN_AUTOMATION: true

    defaults:
      run:
        working-directory: infra/envs/${{ inputs.ENV || 'dev' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Terraform Cloud token
        if: github.event_name != 'pull_request'
        run: |
          if [ -z "${{ secrets[format('{0}_TFE_TOKEN', inputs.APP || 'myapp')] }}" ]; then
            echo "::error::Missing Terraform Cloud token"
            exit 1
          fi

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.0
          cli_config_credentials_token: ${{ secrets[format('{0}_TFE_TOKEN', inputs.APP || 'myapp')] }}

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          echo "Running Terraform PLAN (CI) for ${{ inputs.ENV || 'dev' }} environment"
          terraform plan -no-color